// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const updatePageRank = `-- name: UpdatePageRank :batchexec
UPDATE urls SET page_rank = $2
WHERE url = $1
`

type UpdatePageRankBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpdatePageRankParams struct {
	Url      string  `json:"url"`
	PageRank float64 `json:"page_rank"`
}

func (q *Queries) UpdatePageRank(ctx context.Context, arg []UpdatePageRankParams) *UpdatePageRankBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Url,
			a.PageRank,
		}
		batch.Queue(updatePageRank, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpdatePageRankBatchResults{br, len(arg), false}
}

func (b *UpdatePageRankBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpdatePageRankBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
