// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
)

const getLinks = `-- name: GetLinks :many
WITH discovered_urls AS (
	SELECT "from" AS url FROM links
	UNION
	SELECT "to" AS url FROM links
)
SELECT discovered_urls.url,
ARRAY_AGG( DISTINCT backlinks."from") AS backlinks,
COUNT(DISTINCT outlinks.to) AS outlinks_count
FROM discovered_urls
LEFT JOIN links AS backlinks ON discovered_urls.url = backlinks.to
LEFT JOIN links AS outlinks ON discovered_urls.url = outlinks."from"
GROUP BY discovered_urls.url
`

type GetLinksRow struct {
	Url           string      `json:"url"`
	Backlinks     interface{} `json:"backlinks"`
	OutlinksCount int64       `json:"outlinks_count"`
}

func (q *Queries) GetLinks(ctx context.Context) ([]GetLinksRow, error) {
	rows, err := q.db.Query(ctx, getLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinksRow
	for rows.Next() {
		var i GetLinksRow
		if err := rows.Scan(&i.Url, &i.Backlinks, &i.OutlinksCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
