// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const createRobotRules = `-- name: CreateRobotRules :exec
INSERT INTO robot_rules (
  domain, rules_json
) VALUES (
  $1, $2
) ON CONFLICT (domain)
DO UPDATE SET
	rules_json = EXCLUDED.rules_json,
	fetched_at = NOW()
`

type CreateRobotRulesParams struct {
	Domain    string
	RulesJson []byte
}

func (q *Queries) CreateRobotRules(ctx context.Context, arg CreateRobotRulesParams) error {
	_, err := q.db.Exec(ctx, createRobotRules, arg.Domain, arg.RulesJson)
	return err
}

const getRobotRules = `-- name: GetRobotRules :one
SELECT domain, rules_json, fetched_at FROM robot_rules
WHERE domain = $1
`

func (q *Queries) GetRobotRules(ctx context.Context, domain string) (RobotRule, error) {
	row := q.db.QueryRow(ctx, getRobotRules, domain)
	var i RobotRule
	err := row.Scan(&i.Domain, &i.RulesJson, &i.FetchedAt)
	return i, err
}
