// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type RobotRule struct {
	Domain    string           `json:"domain"`
	RulesJson []byte           `json:"rules_json"`
	FetchedAt pgtype.Timestamp `json:"fetched_at"`
}

type Url struct {
	Url            string           `json:"url"`
	Title          string           `json:"title"`
	Description    string           `json:"description"`
	ContentSummary string           `json:"content_summary"`
	PageRank       float64          `json:"page_rank"`
	CrawledAt      pgtype.Timestamp `json:"crawled_at"`
}

type WordDatum struct {
	Word          string  `json:"word"`
	Url           string  `json:"url"`
	PositionBits  []byte  `json:"position_bits"`
	TermFrequency int32   `json:"term_frequency"`
	Idf           float64 `json:"idf"`
	TfIdf         float64 `json:"tf_idf"`
}
