// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertWordDataParams struct {
	Word          string `json:"word"`
	Url           string `json:"url"`
	PositionBits  []byte `json:"position_bits"`
	TermFrequency int32  `json:"term_frequency"`
}

const insertUrlData = `-- name: InsertUrlData :exec
INSERT INTO urls (url, title, description, content_summary, crawled_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUrlDataParams struct {
	Url            string           `json:"url"`
	Title          string           `json:"title"`
	Description    string           `json:"description"`
	ContentSummary string           `json:"content_summary"`
	CrawledAt      pgtype.Timestamp `json:"crawled_at"`
}

// Url Data Queries
func (q *Queries) InsertUrlData(ctx context.Context, arg InsertUrlDataParams) error {
	_, err := q.db.Exec(ctx, insertUrlData,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.ContentSummary,
		arg.CrawledAt,
	)
	return err
}
