// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchInsertLinks = `-- name: BatchInsertLinks :batchexec
INSERT INTO links (
  "from", "to"
) VALUES (
  $1, $2
) ON CONFLICT ("from", "to")
DO NOTHING
`

type BatchInsertLinksBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertLinksParams struct {
	From int64
	To   int64
}

func (q *Queries) BatchInsertLinks(ctx context.Context, arg []BatchInsertLinksParams) *BatchInsertLinksBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.From,
			a.To,
		}
		batch.Queue(batchInsertLinks, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertLinksBatchResults{br, len(arg), false}
}

func (b *BatchInsertLinksBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertLinksBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertUrls = `-- name: InsertUrls :batchone
INSERT INTO urls (url) VALUES (
  $1
) ON CONFLICT (url)
DO UPDATE SET
	url = urls.url
RETURNING id
`

type InsertUrlsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) InsertUrls(ctx context.Context, url []string) *InsertUrlsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range url {
		vals := []interface{}{
			a,
		}
		batch.Queue(insertUrls, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertUrlsBatchResults{br, len(url), false}
}

func (b *InsertUrlsBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *InsertUrlsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
