// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchInsertLinks = `-- name: BatchInsertLinks :batchexec
INSERT INTO links (
  "from", "to"
) VALUES (
  $1, $2
) ON CONFLICT ("from", "to")
DO NOTHING
`

type BatchInsertLinksBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertLinksParams struct {
	From string
	To   string
}

func (q *Queries) BatchInsertLinks(ctx context.Context, arg []BatchInsertLinksParams) *BatchInsertLinksBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.From,
			a.To,
		}
		batch.Queue(batchInsertLinks, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertLinksBatchResults{br, len(arg), false}
}

func (b *BatchInsertLinksBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertLinksBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
