// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	From string
	To   string
}

type RobotRule struct {
	Domain    string
	RulesJson []byte
	FetchedAt pgtype.Timestamp
}

type Url struct {
	Url            string
	Title          string
	Description    string
	ContentSummary string
	PageRank       pgtype.Float8
	CrawledAt      pgtype.Timestamp
}

type WordDatum struct {
	Word          string
	Url           string
	PositionBits  []byte
	TermFrequency int32
	Idf           pgtype.Float8
	TfIdf         pgtype.Float8
}
