// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
)

const getIndexedWords = `-- name: GetIndexedWords :many
SELECT DISTINCT word from word_data
`

func (q *Queries) GetIndexedWords(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getIndexedWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var word string
		if err := rows.Scan(&word); err != nil {
			return nil, err
		}
		items = append(items, word)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSearchResultCount = `-- name: GetSearchResultCount :one
SELECT COUNT(DISTINCT u.url) as total_results
FROM urls u 
JOIN word_data wd ON u.url = wd.url
WHERE wd.word = ANY($1::text[])
`

func (q *Queries) GetSearchResultCount(ctx context.Context, dollar_1 []string) (int64, error) {
	row := q.db.QueryRow(ctx, getSearchResultCount, dollar_1)
	var total_results int64
	err := row.Scan(&total_results)
	return total_results, err
}

const getSearchResults = `-- name: GetSearchResults :many
SELECT u.url, u.title, u.description, u.content_summary, u.page_rank, COUNT(DISTINCT wd.word) as word_match_count, ARRAY_AGG(wd.word) matched_words, (0.5 * SUM(wd.tf_idf)::DOUBLE PRECISION + 0.5 * u.page_rank) AS combined_score
FROM urls u JOIN word_data wd
ON u.url = wd.url
WHERE wd.word = ANY($1::text[])
GROUP BY u.url ORDER BY word_match_count DESC, combined_score DESC LIMIT $2 OFFSET $3
`

type GetSearchResultsParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

type GetSearchResultsRow struct {
	Url            string      `json:"url"`
	Title          string      `json:"title"`
	Description    string      `json:"description"`
	ContentSummary string      `json:"content_summary"`
	PageRank       float64     `json:"page_rank"`
	WordMatchCount int64       `json:"word_match_count"`
	MatchedWords   interface{} `json:"matched_words"`
	CombinedScore  int32       `json:"combined_score"`
}

func (q *Queries) GetSearchResults(ctx context.Context, arg GetSearchResultsParams) ([]GetSearchResultsRow, error) {
	rows, err := q.db.Query(ctx, getSearchResults, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSearchResultsRow
	for rows.Next() {
		var i GetSearchResultsRow
		if err := rows.Scan(
			&i.Url,
			&i.Title,
			&i.Description,
			&i.ContentSummary,
			&i.PageRank,
			&i.WordMatchCount,
			&i.MatchedWords,
			&i.CombinedScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
