// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForCreateUrls implements pgx.CopyFromSource.
type iteratorForCreateUrls struct {
	rows                 []CreateUrlsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateUrls) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateUrls) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Url,
		r.rows[0].FetchedAt,
	}, nil
}

func (r iteratorForCreateUrls) Err() error {
	return nil
}

func (q *Queries) CreateUrls(ctx context.Context, arg []CreateUrlsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"urls"}, []string{"id", "url", "fetched_at"}, &iteratorForCreateUrls{rows: arg})
}
