// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID         string
	Url        string
	StatusCode pgtype.Int4
	FetchedAt  pgtype.Timestamp
}
