// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RobotRule struct {
	Domain    string
	RulesJson []byte
	FetchedAt pgtype.Timestamp
}

type Url struct {
	Url       string
	FetchedAt pgtype.Timestamp
}
