// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InvertedIndex struct {
	Word         string
	DocumentBits []byte
	DocFrequency int64
}

type Link struct {
	From string
	To   string
}

type RobotRule struct {
	Domain    string
	RulesJson []byte
	FetchedAt pgtype.Timestamp
}

type Url struct {
	ID        int64
	Url       string
	PageRank  pgtype.Float8
	FetchedAt pgtype.Timestamp
}

type UrlDatum struct {
	UrlID       int64
	Title       string
	Description string
	RawContent  string
}

type WordDatum struct {
	Word          string
	UrlID         int64
	PositionBits  []byte
	TermFrequency int32
	Idf           pgtype.Float8
	TfIdf         pgtype.Float8
}
