// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchGetInvertedIndexByWord = `-- name: BatchGetInvertedIndexByWord :batchone
SELECT word, document_bits
FROM inverted_index
WHERE word = $1
`

type BatchGetInvertedIndexByWordBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchGetInvertedIndexByWordRow struct {
	Word         string `json:"word"`
	DocumentBits []byte `json:"document_bits"`
}

// Inverted Index Queries
func (q *Queries) BatchGetInvertedIndexByWord(ctx context.Context, word []string) *BatchGetInvertedIndexByWordBatchResults {
	batch := &pgx.Batch{}
	for _, a := range word {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchGetInvertedIndexByWord, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchGetInvertedIndexByWordBatchResults{br, len(word), false}
}

func (b *BatchGetInvertedIndexByWordBatchResults) QueryRow(f func(int, BatchGetInvertedIndexByWordRow, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i BatchGetInvertedIndexByWordRow
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&i.Word, &i.DocumentBits)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *BatchGetInvertedIndexByWordBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
