// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InvertedIndex struct {
	Word         string `json:"word"`
	DocumentBits []byte `json:"document_bits"`
	DocFrequency int64  `json:"doc_frequency"`
}

type RobotRule struct {
	Domain    string           `json:"domain"`
	RulesJson []byte           `json:"rules_json"`
	FetchedAt pgtype.Timestamp `json:"fetched_at"`
}

type Url struct {
	ID        int64            `json:"id"`
	Url       string           `json:"url"`
	FetchedAt pgtype.Timestamp `json:"fetched_at"`
}

type UrlDatum struct {
	UrlID       int64  `json:"url_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	RawContent  string `json:"raw_content"`
}

type WordDatum struct {
	Word          string        `json:"word"`
	UrlID         int64         `json:"url_id"`
	PositionBits  []byte        `json:"position_bits"`
	TermFrequency int32         `json:"term_frequency"`
	Idf           pgtype.Float8 `json:"idf"`
	TfIdf         pgtype.Float8 `json:"tf_idf"`
}
