// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const updateTfIdf = `-- name: UpdateTfIdf :exec
WITH total_docs AS (
    SELECT COUNT(DISTINCT url)::DOUBLE PRECISION as total 
    FROM word_data
),
word_stats AS (
    SELECT 
        word,
        COUNT(DISTINCT url) as doc_count
    FROM word_data
    GROUP BY word
)
UPDATE word_data wd
SET 
    idf = 1 + (ln((SELECT total FROM total_docs) / ws.doc_count::DOUBLE PRECISION)),
    tf_idf = term_frequency * (1+ ln((SELECT total FROM total_docs) / ws.doc_count::DOUBLE PRECISION))
FROM word_stats ws
WHERE wd.word = ws.word
`

func (q *Queries) UpdateTfIdf(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateTfIdf)
	return err
}
