// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InvertedIndex struct {
	Word         string
	DocumentBits []byte
}

type Metadata struct {
	UrlID           pgtype.UUID
	Title           pgtype.Text
	MetaTitle       pgtype.Text
	MetaDescription pgtype.Text
	MetaRobots      pgtype.Text
}

type RobotRule struct {
	Domain    string
	RulesJson []byte
	FetchedAt pgtype.Timestamp
}

type Url struct {
	ID        pgtype.UUID
	Url       string
	FetchedAt pgtype.Timestamp
}

type WordDatum struct {
	Word          string
	UrlID         pgtype.UUID
	PositionBits  []byte
	TermFrequency int32
}
